apiVersion: skaffold/v1beta11
kind: Config
# Default configuration
build:
  artifacts:
  - image: agent
    context: docker/agent
  - image: am
    context: docker/am
  - image: amster
    context: docker/amster
  - image: idm
    context: docker/idm
  - image: ds-cts
    context: docker/ds/cts
  - image: ds-idrepo
    context: docker/ds/idrepo
  - image: ig
    context: docker/ig
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    path: ./kustomize/env/example
profiles:
- name: pentest
  build:
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/env/pentest
# Run just agent
- name: agent
  build:
    artifacts:
    - image: agent
      context: docker/agent
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/agent
# Run just ig
- name: ig
  build:
    artifacts:
    - image: ig
      context: docker/ig
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/ig
# Run ig and pentest app
- name: ig-app
  build:
    artifacts:
    - image: ig
      context: docker/ig
    tagPolicy:
      sha256: {}
  deploy:
    kustomize:
      path: ./kustomize/env/ig-app
# Run just idm
- name: idm
  build:
    artifacts:
    - image: ds-idrepo
      context: docker/ds/idrepo
    - image: idm
      context: docker/idm
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      path: ./kustomize/env/idm
# Deploy just the small cluster
- name: small
  deploy:
    kustomize:
      path: ./kustomize/env/small